In [1]:
import numpy as np

In [3]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [6]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [7]:
A = np.random.randn(10)
A

array([ 0.56079886,  1.05531657,  0.92723581, -0.61176824,  0.7184979 ,
        0.58868785, -1.3205217 , -0.71867156, -0.70165273,  0.17871188])

In [8]:
B = np.random.randn(10)
B

array([ 0.03390748,  0.17808006, -1.30641377, -0.17792731,  0.04112072,
       -0.17835418,  0.0924646 , -1.2663797 ,  1.26619956, -0.02467816])

In [9]:
# Binary Functions
np.add(A,B)

array([ 0.59470634,  1.23339663, -0.37917796, -0.78969555,  0.75961862,
        0.41033368, -1.2280571 , -1.98505126,  0.56454683,  0.15403372])

In [10]:
np.maximum(A,B)

array([ 0.56079886,  1.05531657,  0.92723581, -0.17792731,  0.7184979 ,
        0.58868785,  0.0924646 , -0.71867156,  1.26619956,  0.17871188])